# -*- coding: utf-8 -*-
"""twenty-seven-letters

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_mGOLUqlQPuPfjthaYkTHrZPxPdHFRs
"""

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage

app = Flask(__name__)

linebot_api = LineBotApi("OLKRxtVlfvIZsd94J+dya7V26fd2Le6F/At72zgCZFRAJI+Ic+m3s\
+OswwQaXWHOqTRNF7x1PSNk0Cbl148U829JujoHQTViAq0VoAWuGxNQ7Qfk6wFcACFvQ4ia9nWfTPNL\
75GoiqpTyK9LcocicAdB04t89/1O/w1cDnyilFU=")
handler = WebhookHandler("70950ac2ab38558fe04e5168ac702b82")

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers["X-Line-Signature"]
    body = request.get_data(as_text=True)

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'
  
@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    linebot_api.reply_message(event.reply_token, \
                               TextSendMessage(text=event.message.text))
  
if __name__ == '__main__':
    app.run()